### ISSUE TITLE
Option to specify git location?

### ISSUE THREAD

**Issue by Jeradin** [aptalca/docker-plexrequests#1]
Again, thanks for creating this, really liking docker and how easy it is.

Was thinking it might be nice to be prompted for a git location incase someone wanted to use their own fork? For me I customize the title, text and some other basic HTML content.

Cheers!

**Comment by aptalca** [comment]
I'd rather keep it as simple as possible. More options mean more support required on my part and I don't have a whole lot of time for development work.

However, you can easily switch github repos once installed.

If you look in the firstrun.sh file, which runs every time the container is started, you'll see that the only time the github repo is specified is if the plexrequests-meteor folder does not exist in the local config folder. Then the script does a git clone of the repo. If you modify that file, you can trick it to pull from a different repo.

Here's how you can switch:
After you create this container, while it is running, exec into the container with "docker exec -it PlexRequests bash" (this will get you into the container's terminal)
Find firstrun.sh at /etc/my_init.d/firstrun.sh
Modify line 7 to change the repo to https://github.com/Jeradin/plexrequests-meteor.git
Exit and stop the container "docker stop PlexRequests"
Delete the plexrequests-meteor folder from your local config folder
Restart the container "docker start PlexRequests"

When the modified firstrun.sh runs and finds the folder missing, it will clone your repo. After that, as long as the local folder exists, it will only do a git pull for updates. Even if you update, or reinstall the container, you should still be fine as the new container won't touch the local plexrequests-meteor folder other than doing a git pull at start.

**Comment by aptalca** [comment]
Oh, wait, hold on. I had a long day at work so I wasn't thinking clearly. There is a much easier way.

While the container is stopped, just delete the local plexrequests-meteor folder and clone from your repo, replacing it. As long as the name of the folder matches, the container won't touch it other than doing a git pull on it at every start.

**Comment by Jeradin** [comment]
Great, thanks!
