### ISSUE TITLE
Reverse Proxy not working.

### ISSUE THREAD

**Issue by kylerw** [aptalca/docker-plexrequests#6]
When I add the parameter for reverse proxy it fails to start.

**Comment by aptalca** [comment]
I'm gonna need more info.

What docker run command are you using? What error are you getting? What platform are you on?

**Comment by kylerw** [comment]
Sorry, left this as I was running out the door to a meeting. unRAID and passing the ROOT_URL="http://localhost/requests"

Then the container is no longer accessible from host:port or using /requests

**Comment by kylerw** [comment]
Full command:

docker run -d --name="PlexRequests" --net="bridge" -e BRANCH="master" -e ROOT_URL="http://localhost/requests" -e TZ="America/Denver" -p 8091:3000/tcp -v "/mnt/cache/Apps/plexrequests":"/config":rw --cpuset-cpus=0 aptalca/docker-plexrequests

**Comment by aptalca** [comment]
Your settings seem right.

First question I have is, whether you waited a few minutes after starting the container. At startup, it updates meteor before the GUI comes up and sometimes meteor's server can be slow and it takes several minutes.

If you wait a while and it still doesn't come up, please post your log and it should tell what's wrong.

**Comment by kylerw** [comment]
@aptalca that was it. I let it sit for a while and it finally finished. Must have hit a Meteor update that was taking forever. Thanks for the help.
